apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: brewery-service-monitor
  namespace: default
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: brewery
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/managed-by: quarkus
      app: brewery
  endpoints:
    - port: http
      path: /q/metrics
      interval: 30s