apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brewery-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
    - http:
        paths:
        - path: /beers
          pathType: Prefix
          backend:
            service:
              name: brewery
              port:
                number: 80